#!/usr/bin/env bash
## Automatic Installation BlanckArm on Termux android
## Authur Salar Muhammadi
#####################################################
chmod +x ~/additional.sh;
bash ~/additional.sh;
clear;
! [[ -f ~/xfce_de.sh ]] && wget https://raw.githubusercontent.com/blanckth/blanckarm/main/vnc/xfce_de.sh -O ~/xfce_de.sh;
chmod +x ~/xfce_de.sh;
bash ~/xfce_de.sh;
clear;
! [[ -f /usr/local/bin/vncserver-start ]] && wget https://raw.githubusercontent.com/blanckth/blanckarm/main/vncserver-start -P /usr/local/bin/;
! [[ -f /usr/local/bin/vncserver-stop ]] && wget https://raw.githubusercontent.com/blanckth/blanckarm/main/vncserver-stop -P /usr/local/bin/;
chmod +x /usr/local/bin/vncserver-stop;
chmod +x /usr/local/bin/vncserver-start;
! [[ -f /usr/bin/vncserver ]] && pacman -S --needed tigervnc --noconfirm;
pacman -S --needed firefox --noconfirm;
clear;
echo 'Welcome to Arch Linux | XFCE';
vncserver-start;
vncserver -list;
echo "Now you can reach Desktop with VNC APP at localhost:13";
echo "You can use vncserver-start and vncserver-stop for Desktop Env";
rm "$folder/root/.bash_profile";
